<!Doctype html>
<html>
    <head>
	<meta charset="utf8">
	<title>Alexis Peters</title>
	<?= $this->meta('charset', 'UTF-8') ?>
	<?= $this->styleSheet('css/bootstrap.min.css') ?>
	<?= $this->styleSheet('css/bootstrap-theme.min.css') ?>
	<?= $this->styleSheet('css/theme.css') ?>
	<?= $this->script('js/jquery-2.1.4.min.js') ?>
	<?= $this->script('js/bootstrap.min.js') ?>
    </head>
    <body>
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Alexis Peters</a>
		    
                </div>
		<?php if(count($this->aRoutes)): ?>
		<div class="navbar-collapse collapse">
		    <ul class="nav navbar-nav">
			<?php foreach($this->aRoutes as $oRoute): ?> 
			<li>
			    <a href="<?= $oRoute->path?>"><?= $oRoute->name ?></a>
			</li>
			<?php endforeach ; ?>
		    </ul>
		</div>
		<?php endif; ?>
            </div>
        </nav>
	<div class="container">
	    <main>
		
		<?= $this->site->display(); ?>
	    </main>
	</div>
	
	<footer>
	    <div class="foo">
		<div class="container">
		    <span class="pull-right">Theme by <a href="http://getbootstrap.com" target="_blank">Bootstrap</a></span>
		</div>
	    </div>
	</footer>
    </body>
</html>